apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: static-capacity
spec:
  replicas: 2
  template:
    spec:
      requirements:
      - key: node.kubernetes.io/instance-type
        operator: In
        values: c7i.xlarge
      taints:
      - key: node.kubernetes.io/instance-type
        value: "equal"
        effect: NoSchedule
  limits:
    nodes: 15  # Maximum nodes during scaling/drift
  disruption:
    budgets:
    - nodes: 20%  # Disruption budget for drift replacement
